name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    name: Checkout Code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

  setup-java:
    name: Set Up JDK 17
    runs-on: ubuntu-latest
    needs: checkout

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Verify Java installation
      run: java -version

  build:
    name: Build with Gradle
    runs-on: ubuntu-latest
    needs: setup-java

    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean project
      run: ./gradlew clean

    - name: Build project
      run: ./gradlew build

    - name: Verify build output
      run: ls -la app/build/outputs/apk/debug/

  upload-artifact:
    name: Upload Build Artifact
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Upload APK
      uses: actions/upload-artifact@v4.3.4
      with:
        name: Aadhan.apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Verify artifact upload
      run: |
        echo "Artifact Aadhan.apk uploaded."
        ls -la
